### ISSUE TITLE
Getting Default Page, instead of Portfolio Website

### ISSUE THREAD

**Issue by euhidaman** [motasimfoad/Portfolio-2020#26]
**Getting Default Page**
I am getting a page as shown in the screenshot. And, It's telling me to add my own index.php file.

![def_page](https://user-images.githubusercontent.com/65843257/130750681-8a119524-7c29-4584-a8c0-57ae8c028918.jpg)

**Expected behavior**
I expected your portfolio website to open. But instead, I am getting the above screenshot.

**Comment by motasimfoad** [comment]
You are absolutely right. I am working towards getting the website live. Thanks for reporting. I appreciate it.

**Comment by motasimfoad** [comment]
Solved, thanks!
